plugins {
    id("groovy")
    id("com.github.johnrengelman.shadow") version "8.1.1"
    id("io.micronaut.library") version "4.1.2"
    id("maven-publish")
    id("codenarc")
    id("java-library")
}

version = "0.0.1-SNAPSHOT"
group = "uk.ac.ox.softeng.mauro"

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    implementation 'uk.ac.ox.softeng.mauro:mauro-domain:0.0.1-SNAPSHOT'
    implementation 'org.apache.groovy:groovy-xml:4.0.21'
    implementation 'org.apache.commons:commons-text:1.12.0'
    testImplementation 'io.micronaut.test:micronaut-test-spock'
}

java {
    sourceCompatibility = JavaVersion.toVersion("17")
    targetCompatibility = JavaVersion.toVersion("17")
    withJavadocJar()
    withSourcesJar()

}

test {
    useJUnitPlatform()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId = 'uk.ac.ox.softeng.mauro.plugins'
            artifactId = 'plugin-xmi-visualparadigm'
            version = "0.0.1-SNAPSHOT"
            from components.java
        }
    }
}

test {
    useJUnitPlatform()
}


codenarc {
    toolVersion = "3.3.0-groovy-4.0"
    configFile = rootProject.file("config/codenarc/codenarc.groovy")
}

codenarcMain {
    compilationClasspath = sourceSets.main.compileClasspath + sourceSets.main.output
}

codenarcTest {
    compilationClasspath = codenarcMain.compilationClasspath + sourceSets.test.compileClasspath + sourceSets.test.output
}

[codenarcMain, codenarcTest]*.ignoreFailures = true
